# Site settings
title: Prairie Native
email: prairienative@gmail.com
description: Life. Roots. Art.  And FIRE.
twitter_username: sql_ag
github_username:  prairienative

# Build settings
markdown: kramdown
